#!/bin/sh
# This script is used to setup my favorite vim plugins

# Check and get pathogen.vim first
if [ ! -d ~/.vim/autoload ]; then
    mkdir -p ~/.vim/autoload ~/.vim/bundle && \
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

# Now put in all favorite vim plugins
cd ~/.vim/bundle

PLUGINS='
https://github.com/vim-scripts/winmanager.git
https://github.com/vim-scripts/taglist.vim.git
https://github.com/vim-scripts/cscope.vim.git
https://github.com/vim-scripts/vim-json-line-format.git
https://github.com/scrooloose/nerdtree.git
https://github.com/fholgado/minibufexpl.vim.git
https://github.com/toyamarinyon/vim-swift.git
https://github.com/vim-scripts/Pydiction.git
https://github.com/Lokaltog/vim-powerline.git
'

for p in $PLUGINS; do
    git clone $p
done

